[workspace]
members = [
    "cli",
    "config",
    "core",
    "logger",
    "template",
    "utils",
    "proc_macro",
    "states",
    "database",
    "http",
    "data_structure",
    "settings"
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
#debug = true
