[database]
timeout = "5s"
max_conn = 50
min_conn = 1
max_lifetime = "12h"
idle_timeout = "1h"
uri = "sqlite:maop_data/default.db"
# Database operations exceeding the specified execution time will issue a warning
warn_time = "3s"

[log]
# Every time it is output to stdout, it will be flushed.
# Turning on this option can prevent the log messages of the console from being confused
# (that is, multiple messages are written to stdout at the same time).
# But in the case of too many log messages, it will seriously slow down the log processing speed.
flush_stdout_every_time = true
full_module_path = false

[log.filter]
# rocket = "warning"
# sqlx = "warning"
